from .alexnet import *
from .resnet import *
from .vgg import *
from .squeezenet import *
from .inception import *
from .densenet import *
from .googlenet import *
from .mobilenet import *
from .mnasnet import *
from .shufflenetv2 import *
from .efficientnet import *
from .regnet import *
from . import segmentation
from . import detection
from . import video
from . import quantization
from . import feature_extraction
