from .alexnet import *
from .resnet import *
from .densenet import *
from .vgg import *
from .efficientnet import *
from .mobilenetv3 import *
from .mobilenetv2 import *
from .mnasnet import *
from .regnet import *
from .shufflenetv2 import *
from . import detection
from . import quantization
from . import segmentation
from . import video
